### ISSUE TITLE
feature request: morse code legend

### ISSUE THREAD

**Issue by herrvonvoid** [fkinoshita/Telegraph#28]
please add a map that shows what which signal sequence represents, so you do not have to look it up on the internet

**Comment by fkinoshita** [comment]
Couldn't you use the regular text input to get the corresponding morse character? e.g if you type "map" it will give you `-- .- .--.`, now you discovered that `M` is `--` and `A` is `.-`, etc...

**Comment by herrvonvoid** [comment]
oh, i get it, didn't think of that
