### ISSUE TITLE
[Feature Request] Morse Code to Message translation.

### ISSUE THREAD

**Issue by begin-theadventure** [fkinoshita/Telegraph#34]
Now it's only possible to translate `Message` to `Morse Code`.

**Comment by fkinoshita** [comment]
You can type on both textviews, if you type on the morse code view it will update the message view as well!

**Comment by begin-theadventure** [comment]
It doesn't work for me, I don't know why.
I compiled it myself, so I don't use Flatpak, I'm not sure if it could be because of that.
