### ISSUE TITLE
Rust?

### ISSUE THREAD

**Issue by fkinoshita** [fkinoshita/Telegraph#4]
GTK Python bindings are not in a good state AFAIK and Rust is super cool!

**Comment by gregorni** [comment]
Are GTK bindings really that bad in Python? I haven't had any great issues with them so far. Also, another thing to keep in mind is that Python attracts more contributors than Rust in my experience. I think Python should be quite fine for a simple app like this.

**Comment by tfuxu** [comment]
They are fine even for bigger projects like Bottles and Gradience.

Python bindings aren't really that bad, but the main problem with them is that they are undermaintained, which means that some functions or behaviors that require overriding may not get implemented as quickly as in other bindings. This hasn't yet in my experience made any issues for me, but I can't say that for everyone.

PyGobject is more than fine for this project, and I would advocate for leaving it in Python, but at the end of a day it is dev's choice what they want to do with this project.

**Comment by gregorni** [comment]
Good point.

**Comment by CarrollMccullough8y** [comment]
Wow, suddenly my interest in learning Rust was piqued.
