### ISSUE TITLE
Two strings seem untranslated

### ISSUE THREAD

**Issue by sabriunal** [fkinoshita/Telegraph#40]
"Message copied" and "Morse code copied" strings seem untranslated. 

![Ekran Görüntüsü - 2023-10-15 13-49-47](https://github.com/fkinoshita/Telegraph/assets/6218679/1f79136a-138a-4837-85a1-871f5daf194b)
![Ekran Görüntüsü - 2023-10-15 13-49-51](https://github.com/fkinoshita/Telegraph/assets/6218679/dc7e357f-5bd4-44e6-87c6-95f388bf33ee)

**Comment by fkinoshita** [comment]
How strange. Does this also happens with Blanket is cases like [this](https://github.com/rafaelmardojai/blanket/blob/master/blanket/window.py#L246)?

Telegraph seem to be using the same function `_` from gettext as other python apps, so not sure what could cause this.

**Comment by sabriunal** [comment]
I believe the second declaration causes the problem. Removing only one line fixed the problem.
